<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Application Debug Mode
	|--------------------------------------------------------------------------
	|
	| When your application is in debug mode, detailed error messages with
	| stack traces will be shown on every error that occurs within the
	| application. When disabled, a simple, generic error is shown.
	|
	*/

	'debug' => true,

	/*
	|--------------------------------------------------------------------------
	| Profiler
	|--------------------------------------------------------------------------
	|
	| When enabled, Laravel's inbuilt front-end profiler will be appended to
	| all output generated by the applications routes.
	|
	*/

	'profiler' => true,

);
