require File.expand_path(File.join(__FILE__, '../../../../support/vagrant_common'))

Vagrant::Config.run do |config|

  config.vm.define :centos6 do |vm_config|
      vm_config.vm.box = "cent63_64"
      vm_config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"
  end

  apply_common_vagrant_config(config)

end
